In [262]:
import pandas as pd
import numpy as np
from python_scripts.utils.feature_selection import *
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GroupKFold

# Classification

In [263]:
final_dataset_path = '../../dataset/final/whole/'
acc_dataset_path = final_dataset_path + 'PatchTable_Acceleration_Filtered.csv'
gyro_dataset_path = final_dataset_path + 'PatchTable_Gyroscope_Filtered.csv'

In [264]:
acc_dataset_df = pd.read_csv(acc_dataset_path)
gyro_dataset_df = pd.read_csv(gyro_dataset_path)
acc_id_pairs = (pd.read_csv(final_dataset_path + 'PatchTable_Acceleration_Normalised.csv'))[['Subject']].values
gyro_id_pairs = (pd.read_csv(final_dataset_path + 'PatchTable_Gyroscope_Normalised.csv'))[['Subject']].values

In [265]:
gyro_id_pairs

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [5],
       [6],
       [6]])

In [266]:
acc_id_pairs

array([[1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [5],
       [6],
       [6]])

In [267]:
acc_dataset_df

Class  InterQuartileRange_SigComplete_AP  \
0       0                          -0.452761   
1       1                          -0.054259   
2       0                          -0.805942   
3       1                          -0.289066   
4       0                          -0.550220   
5       1                           1.854334   
6       0                          -0.005317   
7       1                           2.448761   
8       0                          -0.893207   
9       1                          -0.397876   
10      0                          -0.422660   
11      1                          -0.431788   

    RelativePower_BelowDomFr_Magnitude  CentroidSpMean_Magnitude  
0                            -0.676916                 -0.092303  
1                             0.522940                  2.227281  
2                            -0.862825                 -0.108542  
3                             0.246958                  1.621542  
4                            -0.747132                 -0.473631  
5                            -0.479493                 -0.277505  
6                            -0.893267                 -1.897663  
7                             0.611405                  0.088414  
8                            -0.781816                 -0.526397  
9                             2.500430                  0.002039  
10                           -0.581239                 -0.429143  
11                            1.140954                 -0.134092

In [268]:
acc_target = acc_dataset_df.iloc[:, 0].copy().values
gyro_target = gyro_dataset_df.iloc[:, 0].copy().values
acc_features = acc_dataset_df.iloc[:, 1:].copy().values
gyro_features = gyro_dataset_df.iloc[:, 1:].copy().values

In [269]:
acc_target

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [270]:
gyro_features

array([[ 2.0081014 , -1.68061471,  2.06283573, -1.1724484 ,  1.01757218,
         0.9649292 ],
       [-0.25835587,  2.11163737,  0.08286107, -0.49128046, -0.60046568,
        -0.13256084],
       [-0.53582523,  0.08603492,  0.76873543, -0.59279016, -0.40217005,
        -0.59284529],
       [ 0.3427882 , -0.39283755, -0.11629117,  0.38101458, -0.87992794,
        -1.11103711],
       [-0.65131254,  0.17194626,  0.13085001,  0.1924012 ,  1.87433752,
         0.9419858 ],
       [ 1.93884686, -0.10966649, -0.19985124,  0.79601264,  0.4867619 ,
        -0.79365987],
       [-1.19793235, -0.16378657, -2.5409332 , -0.60262311, -0.65387359,
         1.99852933],
       [-0.683908  ,  0.67128232,  0.0376755 ,  0.81637719, -0.57451264,
        -0.50211797],
       [-0.70879417, -1.78634531,  0.20359641, -1.02994748, -0.31564788,
         0.97837192],
       [ 0.45005357,  0.45208313, -0.26547619,  0.76369399,  0.9067626 ,
        -1.64886903],
       [-0.83013728, -0.14643972,  0.41456923, -1.

### Logistic Regression

In [271]:
# Assuming X and y are your feature matrix and target vector, respectively

# Initialize the logistic regression model
model = LogisticRegression()

# Initialize lists to store predictions and true labels
predictions = []
true_labels = []

# Initialize GroupKFold cross-validator
group_kfold = GroupKFold(n_splits=len(np.unique(gyro_id_pairs)))

# Iterate over each train-test split
for train_index, test_index in group_kfold.split(gyro_features, gyro_target, groups=gyro_id_pairs):
    # Split data into train and test sets
    X_train, X_test = gyro_features[train_index], gyro_features[test_index]
    y_train, y_test = gyro_target[train_index], gyro_target[test_index]
    
    # Fit the model on the training data
    model.fit(X_train, y_train)
    
    # Make predictions on the test data
    y_pred = model.predict(X_test)
    
    # Store predictions and true labels
    predictions.append(y_pred[0])
    true_labels.append(y_test[0])

# Calculate accuracy
accuracy = accuracy_score(true_labels, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.8333333333333334


### Random Forest

### Support Vector Machine 